// <auto-generated />
namespace PartyService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Update02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update02));
        
        string IMigrationMetadata.Id
        {
            get { return "201412122047263_Update02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
